/// Flutter icons Mis_Iconos
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Mis_Iconos
///      fonts:
///       - asset: fonts/Mis_Iconos.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MisIconos {
  MisIconos._();

  static const _kFontFam = 'MisIconos';
  static const String _kFontPkg=null;

  static const IconData cup_of_drink = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData focus_one = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mind = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData focus = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coffee = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hot_coffee = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coffee_one = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coffee_cup = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
